# EJERCICIO INTEGRADOR 1
 
# PART 1:
/*
	- MASCOTAS: ID, NOMBRE, ID_DUEÑO, SERVICIO
    - PERSONAS: ID, NOMBRE, APELLIDO, COD_ZIP, PHONE
    - DIRECCIONES: ZIP, NOMBRE_ZONA, RUTA
*/
# PART 2:
/*
	- AGREGA UNA PRIMARY KEY AL CAMPO ID EN LAS TABLAS MASCOTAS Y PERSONAS
    - AGREGA UNA FOREIGN LEY AL CAMPO ID_DUEÑO EN LA TABLA MASCOTAS QUE REFERENCIE
		AL CAMPO ID EN LA TABLA PERSONAS
    - AGREGA  UNA FOREIGN KEY AL CAMPO COD_ZIP EN LA TABLA PERSONAS QUE REFERENCIA
		AL CAMPO ZIP EN LA TABLA DIRECCIONES
    - AGREGA UNA COLUMNA LLAMADA EMAIL A LA TABLA PERSONAS
    - AGREGA UNA UNIQUE CONSTRAINT A LA COLUMNA EMAIL DE LA TABLA PERSONAS
    - CAMBIA EL NOMBRE DE LA COLUMNA NOMBRE EN LA TABLA MASCOTAS POR PRIMER_NOMBRE
    - CAMBIA EL TIPO DE DATO A LA COLUMNA RUTA EN LA TABA DIRECCIONES POR CHAR(12)
    */
    
CREATE DATABASE veterinario;
USE veterinario;

CREATE TABLE mascotas (
	id INT NOT NULL PRIMARY KEY,
    nombre VARCHAR(20),
    id_duenio INT NOT NULL,
	servicio INT NOT NULL,
    FOREIGN KEY (id_duenio)
		REFERENCES personas(id)
);

CREATE TABLE personas (
	id INT NOT NULL PRIMARY KEY,
    nombre VARCHAR(20),
    apellido VARCHAR(20),
    cod_zip INT NOT NULL,
    phone INT NOT NULL,
    ADD CONSTRAIclienteclienteclienteidclienteNT FK_COD_ZIP
    FOREIGN KEY (cod_zip)
		REFERENCES direcciones(zip)
);

CREATE TABLE direcciones (
	zip INT NOT NULL PRIMARY KEY,
    nombre_zona VARCHAR(20),
    ruta VARCHAR(20)
);
#AGREGA UNA COLUMNA LLAMADA EMAIL A LA TABLA PERSONAS

ALTER TABLE personas
ADD COLUMN email VARCHAR(20);

ALTER TABLE personas
ADD CONSTRAINT u_email UNIQUE (email);

ALTER TABLE mascotas
CHANGE nombre PRIMER_NOMBRE VARCHAR(8);

ALTER TABLE direcciones
MODIFY ruta char(12);

desc mascotas;
desc personas;
desc direcciones;






    